import { Movement } from '../../movement/Movement.js';
import {
  Edge,
  Leg,
  RotationDegree,
  RotationDirection,
  TransitionDirection,
} from '../../enums/movement-enums.js';

export const movements: Movement[] = [
  {
    id: 'ID2',
    name: 'фонарик вперёд',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID3',
    name: 'фонарик назад',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID4',
    name: 'кроссролл вперёд с левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID5',
    name: 'кроссролл вперёд с правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID6',
    name: 'кроссролл назад с левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID7',
    name: 'кроссролл назад с правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID8',
    name: 'верёвочка на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID9',
    name: 'верёвочка на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID10',
    name: 'внутренний аксель на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID11',
    name: 'внутренний аксель на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID12',
    name: 'циркуль вперед внутрь на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID13',
    name: 'циркуль назад внутрь на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID14',
    name: 'циркуль вперед наружу на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID15',
    name: 'циркуль назад наружу на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID16',
    name: 'циркуль назад внутрь на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID17',
    name: 'циркуль вперед внутрь на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID18',
    name: 'циркуль назад наружу на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID19',
    name: 'циркуль вперед наружу на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID20',
    name: 'козлик с левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID21',
    name: 'козлик с правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID22',
    name: 'выпад вперёд наружу на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID23',
    name: 'выпад вперёд наружу на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID24',
    name: 'выпад вперёд внутрь на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID25',
    name: 'выпад вперёд внутрь на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID26',
    name: 'выпад назад наружу на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID27',
    name: 'выпад назад наружу на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID28',
    name: 'выпад назад внутрь на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID29',
    name: 'выпад назад внутрь на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID30',
    name: 'выпад вперёд на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID31',
    name: 'выпад вперёд на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID32',
    name: 'выпад назад на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID33',
    name: 'выпад назад на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID34',
    name: 'подсечка вперёд на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID35',
    name: 'подсечка вперёд на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID36',
    name: 'подсечка назад на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID37',
    name: 'подсечка назад на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID38',
    name: 'кораблик наружу в право',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID39',
    name: 'кораблик наружу в лево',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID40',
    name: 'кораблик внутрь в право',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID41',
    name: 'кораблик внутрь в лево',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID42',
    name: 'бауэр внутрь на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID43',
    name: 'бауэр внутрь на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID44',
    name: 'бауэр наружу на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID45',
    name: 'бауэр наружу на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID46',
    name: 'боковая подпрыжка правым боком',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID47',
    name: 'боковая подпрыжка левым боком',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID48',
    name: 'простая подпрыжка вперёд на левой на правую',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID49',
    name: 'простая подпрыжка вперёд на правой на левую',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID50',
    name: 'простая подпрыжка назад на левой на правую',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID51',
    name: 'простая подпрыжка назад на правой на левую',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID52',
    name: 'подпрыжка вперёд на левой на правую с полным поворотом в право',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID53',
    name: 'подпрыжка вперёд на левой на правую с полным поворотом в лево',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID54',
    name: 'подпрыжка назад на левой на правую с полуповоротом в право',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID55',
    name: 'подпрыжка назад на левой на правую с полуповоротом в лево',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID56',
    name: 'подпрыжка вперёд на правой на левую с полным поворотом в право',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID57',
    name: 'подпрыжка вперёд на правой на левую с поворотом в лево',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID58',
    name: 'подпрыжка назад на правой на левую с полуповоротом в право',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID59',
    name: 'подпрыжка назад на правой на левую с полуповоротом в лево',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID60',
    name: 'перетяжка вперёд внутрь на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID61',
    name: 'перетяжка вперёд наружу на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID62',
    name: 'перетяжка назад внутрь на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID63',
    name: 'перетяжка назад наружу на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID64',
    name: 'перетяжка вперёд внутрь на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID65',
    name: 'перетяжка вперёд наружу на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID66',
    name: 'перетяжка назад внутрь на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID67',
    name: 'перетяжка назад наружу на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID68',
    name: 'шоссе на правой на левую',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID69',
    name: 'шоссе на левой на правую',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID70',
    name: 'моухок вперёд внутрь на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID71',
    name: 'моухок вперёд внутрь на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID72',
    name: 'моухок вперёд наружу на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID73',
    name: 'моухок вперёд наружу на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID74',
    name: 'толчок с хода назад вперёд наружу на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID75',
    name: 'толчок с хода назад вперёд наружу на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID76',
    name: 'толчок ходом назад внутрь назад внутрь на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID77',
    name: 'толчок ходом назад внутрь назад внутрь на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: true,
  },
  {
    id: 'ID78',
    name: 'толчок ходом назад внутрь назад наружу на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID79',
    name: 'толчок ходом назад внутрь назад наружу на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: true,
  },
  {
    id: 'ID80',
    name: 'скрестный шаг назад наружу на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID81',
    name: 'скрестный шаг назад наружу на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID82',
    name: 'тройка вперед наружу на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID83',
    name: 'тройка вперед внутрь на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID84',
    name: 'тройка назад наружу на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID85',
    name: 'тройка назад внутрь на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID86',
    name: 'тройка вперед наружу на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID87',
    name: 'тройка вперед внутрь на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID88',
    name: 'тройка назад наружу на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID89',
    name: 'тройка назад внутрь на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID90',
    name: 'крюк вперед наружу на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID91',
    name: 'крюк вперед внутрь на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID92',
    name: 'крюк назад наружу на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID93',
    name: 'крюк назад внутрь на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID94',
    name: 'крюк вперед наружу на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID95',
    name: 'крюк вперед внутрь на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID96',
    name: 'крюк назад наружу на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID97',
    name: 'крюк назад внутрь на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID98',
    name: 'выкрюк вперед наружу на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID99',
    name: 'выкрюк вперед внутрь на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID100',
    name: 'выкрюк назад наружу на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID101',
    name: 'выкрюк назад внутрь на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID102',
    name: 'выкрюк вперед наружу на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID103',
    name: 'выкрюк вперед внутрь на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID104',
    name: 'выкрюк назад наружу на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID105',
    name: 'выкрюк назад внутрь на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID106',
    name: 'петля вперед наружу на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID107',
    name: 'петля вперед внутрь на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID108',
    name: 'петля назад наружу на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID109',
    name: 'петля назад внутрь на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID110',
    name: 'петля вперед наружу на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID111',
    name: 'петля вперед внутрь на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID112',
    name: 'петля назад наружу на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID113',
    name: 'петля назад внутрь на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID114',
    name: 'выкрюк вперед наружу на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID115',
    name: 'выкрюк вперед внутрь на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID116',
    name: 'выкрюк назад наружу на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID117',
    name: 'выкрюк назад внутрь на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID118',
    name: 'выкрюк вперед наружу на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID119',
    name: 'выкрюк вперед внутрь на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID120',
    name: 'выкрюк назад наружу на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID121',
    name: 'выкрюк назад внутрь на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID122',
    name: 'твизл вперед наружу на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_1080,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID123',
    name: 'твизл вперед внутрь на правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_1080,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID124',
    name: 'твизл назад наружу на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_1080,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID125',
    name: 'твизл назад внутрь на правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_1080,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID126',
    name: 'твизл вперед наружу на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_1080,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID127',
    name: 'твизл вперед внутрь на левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_1080,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID128',
    name: 'твизл назад наружу на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_1080,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID129',
    name: 'твизл назад внутрь на левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_1080,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    isChangeLeg: false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID130',
    name: 'моухок вперёд внутрь с правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID131',
    name: 'моухок вперёд наружу с правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID132',
    name: 'моухок вперёд внутрь с левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID133',
    name: 'моухок вперёд наружу с левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    isChangeEdge: false,
    isSpeedIncrease: false,
  },
  {
    id: 'ID134',
    name: 'чиктао вперёд внутрь с правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID135',
    name: 'чиктао вперёд наружу с правой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID136',
    name: 'чиктао назад наружу с правой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID137',
    name: 'чиктао вперёд внутрь с левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID138',
    name: 'чиктао вперёд наружу с левой',
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
  {
    id: 'ID139',
    name: 'чиктао назад наружу с левой',
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    isChangeLeg: true,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    isChangeEdge: true,
    isSpeedIncrease: false,
  },
];
