import { Movement } from '/home/gen/Backstage/step-sequence-generator/generator-ts/src/movement/Movement.js';
import { Leg, Edge, RotationDirection, RotationDegree, TransitionDirection, MovementCharacter } from '/home/gen/Backstage/step-sequence-generator/generator-ts/src/enums/movement-enums.js';

export const movements: Movement[] =  [
  {
    "id": "ID2",
    "name": "фонарик вперёд",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID3",
    "name": "фонарик назад",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID4",
    "name": "кроссролл вперёд с левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID5",
    "name": "кроссролл вперёд с правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID6",
    "name": "кроссролл назад с левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID7",
    "name": "кроссролл назад с правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID8",
    "name": "верёвочка на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID9",
    "name": "верёвочка на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID10",
    "name": "внутренний аксель на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID11",
    "name": "внутренний аксель на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID12",
    "name": "циркуль вперед внутрь на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID13",
    "name": "циркуль назад внутрь на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID14",
    "name": "циркуль вперед наружу на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID15",
    "name": "циркуль назад наружу на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID16",
    "name": "циркуль назад внутрь на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID17",
    "name": "циркуль вперед внутрь на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID18",
    "name": "циркуль назад наружу на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID19",
    "name": "циркуль вперед наружу на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID20",
    "name": "козлик с левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID21",
    "name": "козлик с правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID22",
    "name": "выпад вперёд наружу на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID23",
    "name": "выпад вперёд наружу на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID24",
    "name": "выпад вперёд внутрь на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID25",
    "name": "выпад вперёд внутрь на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID26",
    "name": "выпад назад наружу на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID27",
    "name": "выпад назад наружу на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID28",
    "name": "выпад назад внутрь на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID29",
    "name": "выпад назад внутрь на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID30",
    "name": "выпад вперёд на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID31",
    "name": "выпад вперёд на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID32",
    "name": "выпад назад на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID33",
    "name": "выпад назад на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID34",
    "name": "подсечка вперёд на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID35",
    "name": "подсечка вперёд на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID36",
    "name": "подсечка назад на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID37",
    "name": "подсечка назад на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID38",
    "name": "кораблик наружу вправо",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "glide",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID39",
    "name": "кораблик наружу влево",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "glide",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID40",
    "name": "кораблик внутрь вправо",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "glide",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID41",
    "name": "кораблик внутрь влево",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "glide",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID42",
    "name": "бауэр внутрь на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "glide",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID43",
    "name": "бауэр внутрь на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "glide",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID44",
    "name": "бауэр наружу на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "glide",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID45",
    "name": "бауэр наружу на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.BOTH,
    endLeg: Leg.BOTH,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "glide",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID46",
    "name": "боковая подпрыжка правым боком",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID47",
    "name": "боковая подпрыжка левым боком",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID48",
    "name": "простая подпрыжка вперёд на левой на правую",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID49",
    "name": "простая подпрыжка вперёд на правой на левую",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID50",
    "name": "простая подпрыжка назад на левой на правую",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID51",
    "name": "простая подпрыжка назад на правой на левую",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.TWO_EDGES,
    endEdge: Edge.TWO_EDGES,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID52",
    "name": "подпрыжка вперёд на левой на правую с полным поворотом вправо",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID53",
    "name": "подпрыжка вперёд на левой на правую с полным поворотом влево",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID54",
    "name": "подпрыжка назад на левой на правую с полуповоротом вправо",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID55",
    "name": "подпрыжка назад на левой на правую с полуповоротом влево",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID56",
    "name": "внутренний козлик в один оборот с левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID57",
    "name": "внутренний козлик в один оборот с правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID58",
    "name": "подпрыжка назад на правой на левую с полуповоротом вправо",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID59",
    "name": "подпрыжка назад на правой на левую с полуповоротом влево",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "hop",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID60",
    "name": "перетяжка вперёд внутрь на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID61",
    "name": "перетяжка вперёд наружу на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID62",
    "name": "перетяжка назад внутрь на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID63",
    "name": "перетяжка назад наружу на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID64",
    "name": "перетяжка вперёд внутрь на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID65",
    "name": "перетяжка вперёд наружу на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID66",
    "name": "перетяжка назад внутрь на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID67",
    "name": "перетяжка назад наружу на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID68",
    "name": "шоссе на правой на левую",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID69",
    "name": "шоссе на левой на правую",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID70",
    "name": "моухок вперёд внутрь на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "step",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID71",
    "name": "моухок вперёд внутрь на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "step",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID72",
    "name": "моухок вперёд наружу на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "step",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID73",
    "name": "моухок вперёд наружу на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "step",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID74",
    "name": "толчок с хода назад вперёд наружу на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID75",
    "name": "толчок с хода назад вперёд наружу на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID76",
    "name": "толчок ходом назад внутрь назад внутрь на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID77",
    "name": "толчок ходом назад внутрь назад внутрь на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID78",
    "name": "толчок ходом назад внутрь назад наружу на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID79",
    "name": "толчок ходом назад внутрь назад наружу на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID80",
    "name": "скрестный шаг назад наружу на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID81",
    "name": "скрестный шаг назад наружу на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.NONE,
    rotationDegree: RotationDegree.DEGREES_0,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "unknown",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID82",
    "name": "тройка вперед наружу на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "turn",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID83",
    "name": "тройка вперед внутрь на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "turn",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID84",
    "name": "тройка назад наружу на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "turn",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID85",
    "name": "тройка назад внутрь на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "turn",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID86",
    "name": "тройка вперед наружу на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "turn",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID87",
    "name": "тройка вперед внутрь на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "turn",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID88",
    "name": "тройка назад наружу на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "turn",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID89",
    "name": "тройка назад внутрь на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "turn",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID90",
    "name": "крюк вперед наружу на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "rocker"
  },
  {
    "id": "ID91",
    "name": "крюк вперед внутрь на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "rocker"
  },
  {
    "id": "ID92",
    "name": "крюк назад наружу на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "rocker"
  },
  {
    "id": "ID93",
    "name": "крюк назад внутрь на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "rocker"
  },
  {
    "id": "ID94",
    "name": "крюк вперед наружу на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "rocker"
  },
  {
    "id": "ID95",
    "name": "крюк вперед внутрь на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "rocker"
  },
  {
    "id": "ID96",
    "name": "крюк назад наружу на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "rocker"
  },
  {
    "id": "ID97",
    "name": "крюк назад внутрь на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "rocker"
  },
  {
    "id": "ID98",
    "name": "выкрюк вперед наружу на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "counter"
  },
  {
    "id": "ID99",
    "name": "выкрюк вперед внутрь на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "counter"
  },
  {
    "id": "ID100",
    "name": "выкрюк назад наружу на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "counter"
  },
  {
    "id": "ID101",
    "name": "выкрюк назад внутрь на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "counter"
  },
  {
    "id": "ID102",
    "name": "выкрюк вперед наружу на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "counter"
  },
  {
    "id": "ID103",
    "name": "выкрюк вперед внутрь на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "counter"
  },
  {
    "id": "ID104",
    "name": "выкрюк назад наружу на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "counter"
  },
  {
    "id": "ID105",
    "name": "выкрюк назад внутрь на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "counter"
  },
  {
    "id": "ID106",
    "name": "петля вперед наружу на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "loop"
  },
  {
    "id": "ID107",
    "name": "петля вперед внутрь на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "loop"
  },
  {
    "id": "ID108",
    "name": "петля назад наружу на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "loop"
  },
  {
    "id": "ID109",
    "name": "петля назад внутрь на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "loop"
  },
  {
    "id": "ID110",
    "name": "петля вперед наружу на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "loop"
  },
  {
    "id": "ID111",
    "name": "петля вперед внутрь на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "loop"
  },
  {
    "id": "ID112",
    "name": "петля назад наружу на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "loop"
  },
  {
    "id": "ID113",
    "name": "петля назад внутрь на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_360,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "loop"
  },
  {
    "id": "ID114",
    "name": "твизл вперед наружу на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_1080,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "twizzle"
  },
  {
    "id": "ID115",
    "name": "твизл вперед внутрь на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_1080,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "twizzle"
  },
  {
    "id": "ID116",
    "name": "твизл назад наружу на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_1080,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "twizzle"
  },
  {
    "id": "ID117",
    "name": "твизл назад внутрь на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_1080,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "twizzle"
  },
  {
    "id": "ID118",
    "name": "твизл вперед наружу на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_1080,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "twizzle"
  },
  {
    "id": "ID119",
    "name": "твизл вперед внутрь на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_1080,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "twizzle"
  },
  {
    "id": "ID120",
    "name": "твизл назад наружу на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_1080,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "twizzle"
  },
  {
    "id": "ID121",
    "name": "твизл назад внутрь на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_1080,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "twizzle"
  },
  {
    "id": "ID122",
    "name": "моухок вперёд внутрь с правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "step",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID123",
    "name": "моухок вперёд наружу с правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "step",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID124",
    "name": "моухок вперёд внутрь с левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.INNER,
    endEdge: Edge.INNER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "step",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID125",
    "name": "моухок вперёд наружу с левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": false,
    "isDifficult": false,
    "type": "step",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID126",
    "name": "чиктао вперёд внутрь с правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "step",
    "description": "",
    "absoluteName": "chocktaw"
  },
  {
    "id": "ID127",
    "name": "чиктао вперёд наружу с правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "step",
    "description": "",
    "absoluteName": "chocktaw"
  },
  {
    "id": "ID128",
    "name": "чиктао назад наружу с правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "step",
    "description": "",
    "absoluteName": "chocktaw"
  },
  {
    "id": "ID129",
    "name": "чиктао вперёд внутрь с левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "step",
    "description": "",
    "absoluteName": "chocktaw"
  },
  {
    "id": "ID130",
    "name": "чиктао вперёд наружу с левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "step",
    "description": "",
    "absoluteName": "chocktaw"
  },
  {
    "id": "ID131",
    "name": "чиктао назад наружу с левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "step",
    "description": "",
    "absoluteName": "chocktaw"
  },
  {
    "id": "ID132",
    "name": "вальсовый шаг с левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "sequence",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID133",
    "name": "вальсовый шаг с правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.LEFT,
    "isChangeLeg": true,
    startEdge: Edge.OUTER,
    endEdge: Edge.OUTER,
    "isChangeEdge": false,
    "isSpeedIncrease": true,
    "isDifficult": false,
    "type": "sequence",
    "description": "",
    "absoluteName": "unknown"
  },
  {
    "id": "ID134",
    "name": "скоба вперед наружу на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "bracket"
  },
  {
    "id": "ID135",
    "name": "скоба вперед внутрь на правой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "bracket"
  },
  {
    "id": "ID136",
    "name": "скоба назад наружу на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "bracket"
  },
  {
    "id": "ID137",
    "name": "скоба назад внутрь на правой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.RIGHT,
    endLeg: Leg.RIGHT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "bracket"
  },
  {
    "id": "ID138",
    "name": "скоба вперед наружу на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "bracket"
  },
  {
    "id": "ID139",
    "name": "скоба вперед внутрь на левой",
    transitionDirection: TransitionDirection.FORWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "bracket"
  },
  {
    "id": "ID140",
    "name": "скоба назад наружу на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.COUNTERCLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.OUTER,
    endEdge: Edge.INNER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "bracket"
  },
  {
    "id": "ID141",
    "name": "скоба назад внутрь на левой",
    transitionDirection: TransitionDirection.BACKWARD,
    rotationDirection: RotationDirection.CLOCKWISE,
    rotationDegree: RotationDegree.DEGREE_180,
    startLeg: Leg.LEFT,
    endLeg: Leg.LEFT,
    "isChangeLeg": false,
    startEdge: Edge.INNER,
    endEdge: Edge.OUTER,
    "isChangeEdge": true,
    "isSpeedIncrease": false,
    "isDifficult": true,
    "type": "turn",
    "description": "",
    "absoluteName": "bracket"
  }
];
